## Scrutinizer quality insurance configuration
before_commands:
  - 'composer install --prefer-source --no-interaction --no-dev'
  - 'composer install:phpunit'

tools:
  external_code_coverage: true
  php_mess_detector:
    config:
      unused_code_rules:
        unused_local_variable: true
        unused_private_method: true
        unused_formal_parameter: true
      controversial_rules:
        camel_case_class_name: true
        camel_case_property_name: true
        camel_case_method_name: true
  php_cs_fixer: true
  php_pdepend: true
  php_sim: true
  php_changetracking: true
  php_analyzer: true
  sensiolabs_security_checker: true

filter:
  excluded_paths:
    - vendor/*
    - test/public/*

build:
  tests:
    before:
      - "bin/phpunit"
