sudo: false
language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
install:
  - composer install --no-interaction --prefer-source
  - composer install:phpunit
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
