sudo: false
language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
install:
  - composer self-update && composer install --no-interaction --prefer-source
script:
  - vendor/bin/atoum
  - vendor/bin/phpcs --standard=phpcs.xml
after_script:
  - |
    echo "
    \$clover = new atoum\\reports\\asynchronous\\clover();
    \$runner->addReport(\$clover);
    \$writer = new atoum\\writers\\file('atoum.clover');
    \$clover->addWriter(\$writer);
    " >> .atoum.php && vendor/bin/atoum
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover atoum.clover
